In [33]:
#1
a=np.random.random((10,3))
print(a) 
np.array([a[np.arange(10),np.argmin((abs(a-0.5)),axis=1)]])

[[0.78267905 0.76078225 0.9731101 ]
 [0.70123202 0.62946703 0.52970687]
 [0.38522954 0.62131194 0.26110665]
 [0.56573266 0.25143631 0.92696728]
 [0.9641425  0.19405582 0.46795424]
 [0.07833212 0.31305275 0.43753726]
 [0.44410515 0.4777997  0.71759243]
 [0.72037609 0.25569306 0.00169975]
 [0.34267212 0.1695146  0.85908692]
 [0.85914821 0.12840813 0.32280918]]


array([[0.76078225, 0.52970687, 0.38522954, 0.56573266, 0.46795424,
        0.43753726, 0.4777997 , 0.72037609, 0.34267212, 0.32280918]])

In [66]:
#2
a=np.random.random((6,6))
print(a)
np.array([np.sum(a,axis=1)/(a[np.argmin(a,axis=0),np.arange(6)])])

[[0.54938012 0.67432487 0.71211869 0.13846191 0.23069731 0.31973915]
 [0.84686966 0.87616693 0.74023849 0.86861491 0.9745244  0.43918775]
 [0.04930059 0.85211163 0.90318844 0.80107128 0.4530225  0.63506087]
 [0.81580245 0.80402477 0.51547261 0.63819161 0.03011451 0.93850027]
 [0.04400931 0.93988915 0.45929912 0.83739362 0.97147223 0.23180034]
 [0.28941824 0.61035942 0.51130632 0.35386671 0.14754591 0.15375094]]


array([[ 59.64015528,   7.77509453,   8.04215627,  27.02624996,
        115.68721207,  13.43892597]])

In [80]:
#3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max(x[np.roll(x,1) == 0][1:])


5

In [4]:
#4
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(x+np.bincount(i,minlength=10))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [114]:
#6
import numpy as np
from scipy.cluster.vq import kmeans #для проверки
data = np.loadtxt('http://www.stat.cmu.edu/~larry/all-of-statistics/=data/faithful.dat', skiprows=26)[:, 1:]
#data = np.genfromtxt('dataset-dz.csv', delimiter=',', skip_header = 1) #загрузили данные
data = data / np.std(data, axis = 0) #отнормировали

def k1_means(pts,k,t=20, eps = 1e-05):
    n=pts.shape[0] #количество точек
    d=pts.shape[1] #размерность наблюдений
    ncentr=pts[:k,:] #сначала центроидами берем первые k точек
    pts=np.expand_dims(pts,axis=1) #добавление размерности в матрицу точек
    centr=np.zeros((k,d))
    ndistort=256
    distort=0
    i=0
    while np.abs(ndistort-distort) > eps and i<t:
        centr=ncentr
        distort=ndistort
        clust=np.argmin(((pts-ncentr)**2).sum(axis=2),axis=1) #по правилу бродкастинга pts-ncentr это матрица n*k*m
        M=np.zeros(n*k*d).reshape(n,k,d)
        M[np.arange(n),clust]=(pts-ncentr)[np.arange(n),clust]/np.bincount(clust)[clust].reshape(n, 1)
        ncentr=centr+M.sum(axis=0)
        clust=np.argmin(((pts-ncentr)**2).sum(axis=2),axis=1) #массив в котором на iом месте стоит номер кластера для iой точки
        M=np.zeros(n*k*d).reshape(n,k,d)
        M[np.arange(n),clust]=(pts-ncentr)[np.arange(n),clust]
        ndistort=np.sqrt((M ** 2).sum(axis=2)).sum(axis=1).mean()
        i=i+1
    return ncentr, ndistort
print(k1_means(data,3))
print(kmeans(data,3))


                                
        
    


(array([[3.94227822, 6.12191001],
       [1.78898054, 4.01584421],
       [3.4837013 , 5.52801374]]), 0.3993167936672239)
(array([[1.78898054, 4.01584421],
       [3.5554264 , 5.55209979],
       [3.94057655, 6.17632623]]), 0.39867033910203986)


In [117]:
#5
a = np.arange(16).reshape(4, 4)
print(a)
b=[np.diagonal(a[:,::-1],k) for k in range (3,-3,-1)]
b


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([0]),
 array([1, 4]),
 array([2, 5, 8]),
 array([ 3,  6,  9, 12]),
 array([ 7, 10, 13]),
 array([11, 14])]